name: macos

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        perl-version:
          - '5.10'
          - '5.12'
        include:
          - perl-version: '5.38'
            coverage: true
    container: 
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure git
        run: git config --system --add safe.directory '*'
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          curl -L https://cpanmin.us | perl - -nq --installdeps .
          curl -L https://cpanmin.us | perl - -n TAP::Formatter::GitHubActions
      - name: Run Tests
        run: prove --merge --formatter TAP::Formatter::GitHubActions -l t
